// EZ designation master list (auto-generated from the org designation table; do not hand-edit).
// dept/team = primary mapping; `autofill` is true only when the title maps to exactly one
// department AND one team (so picking it can safely fill Department & Team). Titles that span
// multiple departments (Manager, Associate, Team Lead, Intern, …) have autofill=false.
export const DESIGNATION_SEEDS = [
  { title: "Account Manager", dept: "Delivery", team: "Audio Visual Team", autofill: false },
  { title: "Accountant", dept: "Finance and Accounting", team: "Accounting", autofill: true },
  { title: "AI Software Engineer", dept: "Technology", team: "Technology", autofill: true },
  { title: "Analyst", dept: "CEOs Office", team: "CEOs Office", autofill: true },
  { title: "Analyst I", dept: "CEOs Office", team: "Product Design", autofill: false },
  { title: "Analyst II", dept: "CEOs Office", team: "Product Design", autofill: true },
  { title: "Analyst III", dept: "CEOs Office", team: "Product Design", autofill: true },
  { title: "Animation Intern", dept: "Delivery", team: "Audio Visual Team", autofill: true },
  { title: "Animator", dept: "Delivery", team: "Audio Visual Team", autofill: true },
  { title: "Arabic Linguist", dept: "Technology", team: "Applied Research", autofill: true },
  { title: "Assistant Creative Director", dept: "Delivery", team: "Audio Visual Team", autofill: true },
  { title: "Assistant Director", dept: "Delivery", team: "Audio Visual Team", autofill: true },
  { title: "Assistant Manager", dept: "Delivery", team: "Operations", autofill: false },
  { title: "Assistant Quality Manager", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "Assistant Vice President (AVP)", dept: "Sales", team: "Sales", autofill: true },
  { title: "Associate", dept: "Delivery", team: "Operations", autofill: false },
  { title: "Associate Director", dept: "Delivery", team: "Delivery", autofill: false },
  { title: "Associate HH", dept: "Administration", team: "Administration", autofill: true },
  { title: "Backend Engineer", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Backend Intern", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Botany Intern", dept: "Administration", team: "Facilities", autofill: true },
  { title: "Brand and Communication Specialist", dept: "CEOs Office", team: "CEOs Office", autofill: true },
  { title: "Brand and Communication Team Lead", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: true },
  { title: "Business Analyst", dept: "Technology", team: "Product Development", autofill: false },
  { title: "Business Analyst Intern", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Business Associate", dept: "CEOs Office", team: "CEOs Office", autofill: false },
  { title: "Business Development Manager", dept: "Sales", team: "Sales", autofill: true },
  { title: "Business Manager", dept: "CEOs Office", team: "CEOs Office", autofill: true },
  { title: "CEO", dept: "CEOs Office", team: "CEOs Office", autofill: true },
  { title: "Chief Operating Officer", dept: "CEOs Office", team: "CEOs Office", autofill: true },
  { title: "Co Founder", dept: "CEOs Office", team: "CEOs Office", autofill: true },
  { title: "Consultant", dept: "Sales", team: "Sales", autofill: false },
  { title: "Content and Communication Associate", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: true },
  { title: "Content Writer", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: false },
  { title: "Content Writing Associate", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: true },
  { title: "Content Writing Intern", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: true },
  { title: "Contractual Expert", dept: "Delivery", team: "Visual Graphics Team", autofill: false },
  { title: "Copywriter", dept: "Delivery", team: "Arabic Language Team", autofill: false },
  { title: "Creative Director", dept: "Delivery", team: "Audio Visual Team", autofill: false },
  { title: "Creative Lead", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "Data Analyst", dept: "CEOs Office", team: "CEOs Office", autofill: false },
  { title: "Data Associate", dept: "Delivery", team: "Research and Data", autofill: true },
  { title: "Data Engineer", dept: "Technology", team: "Applied Research", autofill: true },
  { title: "Data Engineering Intern", dept: "Technology", team: "Applied Research", autofill: true },
  { title: "Data Science Intern", dept: "Technology", team: "Applied Research", autofill: true },
  { title: "Data Scientist", dept: "Technology", team: "Applied Research", autofill: true },
  { title: "Dev Ops Engineer", dept: "Technology", team: "Product Operations", autofill: true },
  { title: "Dev Ops Engineer Intern", dept: "Technology", team: "Product Operations", autofill: true },
  { title: "Dev Ops Manager", dept: "Technology", team: "Technology", autofill: true },
  { title: "Digital Marketing Associate", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: true },
  { title: "Digital Marketing Specialist", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: true },
  { title: "Director", dept: "Delivery", team: "Audio Visual Team", autofill: false },
  { title: "Entrepreneur in Residence", dept: "CEOs Office", team: "CEOs Office", autofill: true },
  { title: "Executive Assistant", dept: "CEOs Office", team: "CEOs Office", autofill: false },
  { title: "Fellow: Level 1", dept: "Delivery", team: "Arabic Language Team", autofill: true },
  { title: "Fellow: Level 2", dept: "Delivery", team: "Arabic Language Team", autofill: true },
  { title: "Frontend Intern", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Graphic Design Intern", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "Graphic Designer", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "Growth Team Lead", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: true },
  { title: "Head", dept: "Technology", team: "Applied Research", autofill: true },
  { title: "Head of Department (HoD)", dept: "Delivery", team: "Delivery", autofill: false },
  { title: "Horticulture Associate", dept: "Administration", team: "Facilities", autofill: true },
  { title: "Housekeeping Trainer HH", dept: "Administration", team: "Administration", autofill: true },
  { title: "HR Specialist", dept: "People", team: "People", autofill: true },
  { title: "Intern", dept: "Delivery", team: "Research and Data", autofill: false },
  { title: "Junior AI Software Engineer", dept: "Technology", team: "Technology", autofill: true },
  { title: "Junior Backend Developer", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Junior Data Scientist", dept: "Technology", team: "Applied Research", autofill: true },
  { title: "Junior Data Scientist II", dept: "Technology", team: "Applied Research", autofill: true },
  { title: "Junior Presentation Designer", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "Junior Software Developer", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Junior Supervisor", dept: "Administration", team: "Facilities", autofill: true },
  { title: "Learning and Development Specialist", dept: "People", team: "People", autofill: true },
  { title: "Linguist", dept: "Delivery", team: "Arabic Language Team", autofill: true },
  { title: "Machine Learning Engineer", dept: "Technology", team: "Applied Research", autofill: true },
  { title: "Machine Learning Scientist", dept: "Technology", team: "Technology", autofill: true },
  { title: "Manager", dept: "Administration", team: "Operations", autofill: false },
  { title: "Market Research and Data Intern", dept: "COOs Office", team: "COOs Office", autofill: true },
  { title: "Market Research Intern", dept: "Delivery", team: "Market Research Team", autofill: true },
  { title: "MR Specialist", dept: "Delivery", team: "Market Research Team", autofill: true },
  { title: "Network Engineer", dept: "Administration", team: "IT", autofill: true },
  { title: "Presentation Design Intern", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "Presentation Designer", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "Presentation Specialist", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "Process Associate I", dept: "CEOs Office", team: "Product Design", autofill: false },
  { title: "Process Associate II", dept: "CEOs Office", team: "Product Design", autofill: true },
  { title: "Process Associate III", dept: "CEOs Office", team: "Product Design", autofill: true },
  { title: "Process Lead", dept: "CEOs Office", team: "Product Design", autofill: true },
  { title: "Process Manager", dept: "CEOs Office", team: "Product Design", autofill: true },
  { title: "Producer", dept: "Delivery", team: "Audio Visual Team", autofill: true },
  { title: "Product Lead", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Product Management Associate", dept: "Technology", team: "Technology", autofill: true },
  { title: "Product Management Associate I", dept: "CEOs Office", team: "Product Design", autofill: true },
  { title: "Product Management Associate II", dept: "CEOs Office", team: "Product Design", autofill: false },
  { title: "Product Management Intern", dept: "Technology", team: "Technology", autofill: true },
  { title: "Product Manager", dept: "Technology", team: "Technology", autofill: false },
  { title: "Project Lead", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Project Management Intern", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Quality Manager", dept: "Delivery", team: "Arabic Language Team", autofill: false },
  { title: "Recruiter", dept: "People", team: "Human Resources", autofill: true },
  { title: "Regional Manager", dept: "Sales", team: "Sales", autofill: true },
  { title: "Research Analyst", dept: "Delivery", team: "Research and Data", autofill: true },
  { title: "Research Associate", dept: "Delivery", team: "Research and Data", autofill: true },
  { title: "Research Lead", dept: "Delivery", team: "Market Research Team", autofill: true },
  { title: "Research Specialist", dept: "Delivery", team: "Market Research Team", autofill: true },
  { title: "Resident Associate", dept: "Administration", team: "Facilities", autofill: true },
  { title: "Sales Associate", dept: "Delivery", team: "Client Relations", autofill: true },
  { title: "Senior Associate", dept: "Administration", team: "Operations", autofill: false },
  { title: "Senior Consultant", dept: "Sales", team: "Sales", autofill: true },
  { title: "Senior Dev Ops Engineer", dept: "Technology", team: "Product Operations", autofill: true },
  { title: "Senior Frontend Developer", dept: "Technology", team: "Technology", autofill: true },
  { title: "Senior Graphic Designer", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "Senior Linguist", dept: "Delivery", team: "Arabic Language Team", autofill: true },
  { title: "Senior Manager", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: true },
  { title: "Senior Project Lead", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Senior SEO Specialist", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: true },
  { title: "Senior Software AI Engineer", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Senior Software Developer", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Senior Software QA Engineer", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Senior Team Lead", dept: "Delivery", team: "Operations", autofill: false },
  { title: "Senior UI Designer", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "Social Media Marketing Intern", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: true },
  { title: "Social Media Specialist", dept: "Branding and Marketing", team: "Branding and Marketing", autofill: true },
  { title: "Software Developer", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Software Developer Intern", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Software Lead", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Software QA Engineer", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Supervisor", dept: "Administration", team: "Facilities", autofill: true },
  { title: "Team Lead", dept: "Delivery", team: "Operations", autofill: false },
  { title: "Team Lead HH", dept: "Administration", team: "Administration", autofill: true },
  { title: "Technology Consultant", dept: "Technology", team: "Technology", autofill: true },
  { title: "Testing Engineer", dept: "Technology", team: "Technology", autofill: false },
  { title: "Trainee", dept: "Technology", team: "Product Development", autofill: true },
  { title: "Translator", dept: "Delivery", team: "Arabic Language Team", autofill: true },
  { title: "UI Designer", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "UI/ UX Designer", dept: "CEOs Office", team: "Product Design", autofill: true },
  { title: "VG Expert", dept: "Delivery", team: "Chinese Visual Graphics Team", autofill: true },
  { title: "VG Master Specialist", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "VG Specialist", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
  { title: "Vice President (VP)", dept: "Sales", team: "Sales", autofill: false },
  { title: "Visual Graphics Associate", dept: "Delivery", team: "Visual Graphics Team", autofill: true },
]

// Sorted list of just the titles — for the dropdown options.
export const DESIGNATION_TITLES = DESIGNATION_SEEDS.map((d) => d.title)

// title -> record, for auto-fill lookup.
export const DESIGNATION_BY_TITLE = Object.fromEntries(DESIGNATION_SEEDS.map((d) => [d.title, d]))
