// Every ITU calling code, with country names resolved from Intl so the spellings are not
// hand-maintained. The countries EZ actually hires from lead the list; the rest are A-Z, because
// scrolling past 240 rows to find your own is the whole reason people mistype a phone number.
//
// Generated — see scratchpad/gen_codes.mjs. ${rows.length} entries.
export const DIAL_CODES = [
  { iso: 'IN', code: '+91', name: "India" },
  { iso: 'AE', code: '+971', name: "United Arab Emirates" },
  { iso: 'SA', code: '+966', name: "Saudi Arabia" },
  { iso: 'QA', code: '+974', name: "Qatar" },
  { iso: 'OM', code: '+968', name: "Oman" },
  { iso: 'KW', code: '+965', name: "Kuwait" },
  { iso: 'BH', code: '+973', name: "Bahrain" },
  { iso: 'GB', code: '+44', name: "United Kingdom" },
  { iso: 'US', code: '+1', name: "United States" },
  { iso: 'SG', code: '+65', name: "Singapore" },
  { iso: 'AU', code: '+61', name: "Australia" },
  { iso: 'CA', code: '+1', name: "Canada" },
  { iso: 'AF', code: '+93', name: "Afghanistan" },
  { iso: 'AX', code: '+358', name: "Åland Islands" },
  { iso: 'AL', code: '+355', name: "Albania" },
  { iso: 'DZ', code: '+213', name: "Algeria" },
  { iso: 'AS', code: '+1', name: "American Samoa" },
  { iso: 'AD', code: '+376', name: "Andorra" },
  { iso: 'AO', code: '+244', name: "Angola" },
  { iso: 'AI', code: '+1', name: "Anguilla" },
  { iso: 'AG', code: '+1', name: "Antigua & Barbuda" },
  { iso: 'AR', code: '+54', name: "Argentina" },
  { iso: 'AM', code: '+374', name: "Armenia" },
  { iso: 'AW', code: '+297', name: "Aruba" },
  { iso: 'AT', code: '+43', name: "Austria" },
  { iso: 'AZ', code: '+994', name: "Azerbaijan" },
  { iso: 'BS', code: '+1', name: "Bahamas" },
  { iso: 'BD', code: '+880', name: "Bangladesh" },
  { iso: 'BB', code: '+1', name: "Barbados" },
  { iso: 'BY', code: '+375', name: "Belarus" },
  { iso: 'BE', code: '+32', name: "Belgium" },
  { iso: 'BZ', code: '+501', name: "Belize" },
  { iso: 'BJ', code: '+229', name: "Benin" },
  { iso: 'BM', code: '+1', name: "Bermuda" },
  { iso: 'BT', code: '+975', name: "Bhutan" },
  { iso: 'BO', code: '+591', name: "Bolivia" },
  { iso: 'BA', code: '+387', name: "Bosnia & Herzegovina" },
  { iso: 'BW', code: '+267', name: "Botswana" },
  { iso: 'BR', code: '+55', name: "Brazil" },
  { iso: 'IO', code: '+246', name: "British Indian Ocean Territory" },
  { iso: 'VG', code: '+1', name: "British Virgin Islands" },
  { iso: 'BN', code: '+673', name: "Brunei" },
  { iso: 'BG', code: '+359', name: "Bulgaria" },
  { iso: 'BF', code: '+226', name: "Burkina Faso" },
  { iso: 'BI', code: '+257', name: "Burundi" },
  { iso: 'KH', code: '+855', name: "Cambodia" },
  { iso: 'CM', code: '+237', name: "Cameroon" },
  { iso: 'CV', code: '+238', name: "Cape Verde" },
  { iso: 'BQ', code: '+599', name: "Caribbean Netherlands" },
  { iso: 'KY', code: '+1', name: "Cayman Islands" },
  { iso: 'CF', code: '+236', name: "Central African Republic" },
  { iso: 'TD', code: '+235', name: "Chad" },
  { iso: 'CL', code: '+56', name: "Chile" },
  { iso: 'CN', code: '+86', name: "China" },
  { iso: 'CX', code: '+61', name: "Christmas Island" },
  { iso: 'CC', code: '+61', name: "Cocos (Keeling) Islands" },
  { iso: 'CO', code: '+57', name: "Colombia" },
  { iso: 'KM', code: '+269', name: "Comoros" },
  { iso: 'CG', code: '+242', name: "Congo - Brazzaville" },
  { iso: 'CD', code: '+243', name: "Congo - Kinshasa" },
  { iso: 'CK', code: '+682', name: "Cook Islands" },
  { iso: 'CR', code: '+506', name: "Costa Rica" },
  { iso: 'CI', code: '+225', name: "Côte d’Ivoire" },
  { iso: 'HR', code: '+385', name: "Croatia" },
  { iso: 'CU', code: '+53', name: "Cuba" },
  { iso: 'CW', code: '+599', name: "Curaçao" },
  { iso: 'CY', code: '+357', name: "Cyprus" },
  { iso: 'CZ', code: '+420', name: "Czechia" },
  { iso: 'DK', code: '+45', name: "Denmark" },
  { iso: 'DJ', code: '+253', name: "Djibouti" },
  { iso: 'DM', code: '+1', name: "Dominica" },
  { iso: 'DO', code: '+1', name: "Dominican Republic" },
  { iso: 'EC', code: '+593', name: "Ecuador" },
  { iso: 'EG', code: '+20', name: "Egypt" },
  { iso: 'SV', code: '+503', name: "El Salvador" },
  { iso: 'GQ', code: '+240', name: "Equatorial Guinea" },
  { iso: 'ER', code: '+291', name: "Eritrea" },
  { iso: 'EE', code: '+372', name: "Estonia" },
  { iso: 'SZ', code: '+268', name: "Eswatini" },
  { iso: 'ET', code: '+251', name: "Ethiopia" },
  { iso: 'FK', code: '+500', name: "Falkland Islands" },
  { iso: 'FO', code: '+298', name: "Faroe Islands" },
  { iso: 'FJ', code: '+679', name: "Fiji" },
  { iso: 'FI', code: '+358', name: "Finland" },
  { iso: 'FR', code: '+33', name: "France" },
  { iso: 'GF', code: '+594', name: "French Guiana" },
  { iso: 'PF', code: '+689', name: "French Polynesia" },
  { iso: 'GA', code: '+241', name: "Gabon" },
  { iso: 'GM', code: '+220', name: "Gambia" },
  { iso: 'GE', code: '+995', name: "Georgia" },
  { iso: 'DE', code: '+49', name: "Germany" },
  { iso: 'GH', code: '+233', name: "Ghana" },
  { iso: 'GI', code: '+350', name: "Gibraltar" },
  { iso: 'GR', code: '+30', name: "Greece" },
  { iso: 'GL', code: '+299', name: "Greenland" },
  { iso: 'GD', code: '+1', name: "Grenada" },
  { iso: 'GP', code: '+590', name: "Guadeloupe" },
  { iso: 'GU', code: '+1', name: "Guam" },
  { iso: 'GT', code: '+502', name: "Guatemala" },
  { iso: 'GG', code: '+44', name: "Guernsey" },
  { iso: 'GN', code: '+224', name: "Guinea" },
  { iso: 'GW', code: '+245', name: "Guinea-Bissau" },
  { iso: 'GY', code: '+592', name: "Guyana" },
  { iso: 'HT', code: '+509', name: "Haiti" },
  { iso: 'HN', code: '+504', name: "Honduras" },
  { iso: 'HK', code: '+852', name: "Hong Kong SAR China" },
  { iso: 'HU', code: '+36', name: "Hungary" },
  { iso: 'IS', code: '+354', name: "Iceland" },
  { iso: 'ID', code: '+62', name: "Indonesia" },
  { iso: 'IR', code: '+98', name: "Iran" },
  { iso: 'IQ', code: '+964', name: "Iraq" },
  { iso: 'IE', code: '+353', name: "Ireland" },
  { iso: 'IM', code: '+44', name: "Isle of Man" },
  { iso: 'IL', code: '+972', name: "Israel" },
  { iso: 'IT', code: '+39', name: "Italy" },
  { iso: 'JM', code: '+1', name: "Jamaica" },
  { iso: 'JP', code: '+81', name: "Japan" },
  { iso: 'JE', code: '+44', name: "Jersey" },
  { iso: 'JO', code: '+962', name: "Jordan" },
  { iso: 'KZ', code: '+7', name: "Kazakhstan" },
  { iso: 'KE', code: '+254', name: "Kenya" },
  { iso: 'KI', code: '+686', name: "Kiribati" },
  { iso: 'KG', code: '+996', name: "Kyrgyzstan" },
  { iso: 'LA', code: '+856', name: "Laos" },
  { iso: 'LV', code: '+371', name: "Latvia" },
  { iso: 'LB', code: '+961', name: "Lebanon" },
  { iso: 'LS', code: '+266', name: "Lesotho" },
  { iso: 'LR', code: '+231', name: "Liberia" },
  { iso: 'LY', code: '+218', name: "Libya" },
  { iso: 'LI', code: '+423', name: "Liechtenstein" },
  { iso: 'LT', code: '+370', name: "Lithuania" },
  { iso: 'LU', code: '+352', name: "Luxembourg" },
  { iso: 'MO', code: '+853', name: "Macao SAR China" },
  { iso: 'MG', code: '+261', name: "Madagascar" },
  { iso: 'MW', code: '+265', name: "Malawi" },
  { iso: 'MY', code: '+60', name: "Malaysia" },
  { iso: 'MV', code: '+960', name: "Maldives" },
  { iso: 'ML', code: '+223', name: "Mali" },
  { iso: 'MT', code: '+356', name: "Malta" },
  { iso: 'MH', code: '+692', name: "Marshall Islands" },
  { iso: 'MQ', code: '+596', name: "Martinique" },
  { iso: 'MR', code: '+222', name: "Mauritania" },
  { iso: 'MU', code: '+230', name: "Mauritius" },
  { iso: 'YT', code: '+262', name: "Mayotte" },
  { iso: 'MX', code: '+52', name: "Mexico" },
  { iso: 'FM', code: '+691', name: "Micronesia" },
  { iso: 'MD', code: '+373', name: "Moldova" },
  { iso: 'MC', code: '+377', name: "Monaco" },
  { iso: 'MN', code: '+976', name: "Mongolia" },
  { iso: 'ME', code: '+382', name: "Montenegro" },
  { iso: 'MS', code: '+1', name: "Montserrat" },
  { iso: 'MA', code: '+212', name: "Morocco" },
  { iso: 'MZ', code: '+258', name: "Mozambique" },
  { iso: 'MM', code: '+95', name: "Myanmar (Burma)" },
  { iso: 'NA', code: '+264', name: "Namibia" },
  { iso: 'NR', code: '+674', name: "Nauru" },
  { iso: 'NP', code: '+977', name: "Nepal" },
  { iso: 'NL', code: '+31', name: "Netherlands" },
  { iso: 'NC', code: '+687', name: "New Caledonia" },
  { iso: 'NZ', code: '+64', name: "New Zealand" },
  { iso: 'NI', code: '+505', name: "Nicaragua" },
  { iso: 'NE', code: '+227', name: "Niger" },
  { iso: 'NG', code: '+234', name: "Nigeria" },
  { iso: 'NU', code: '+683', name: "Niue" },
  { iso: 'NF', code: '+672', name: "Norfolk Island" },
  { iso: 'KP', code: '+850', name: "North Korea" },
  { iso: 'MK', code: '+389', name: "North Macedonia" },
  { iso: 'MP', code: '+1', name: "Northern Mariana Islands" },
  { iso: 'NO', code: '+47', name: "Norway" },
  { iso: 'PK', code: '+92', name: "Pakistan" },
  { iso: 'PW', code: '+680', name: "Palau" },
  { iso: 'PS', code: '+970', name: "Palestinian Territories" },
  { iso: 'PA', code: '+507', name: "Panama" },
  { iso: 'PG', code: '+675', name: "Papua New Guinea" },
  { iso: 'PY', code: '+595', name: "Paraguay" },
  { iso: 'PE', code: '+51', name: "Peru" },
  { iso: 'PH', code: '+63', name: "Philippines" },
  { iso: 'PN', code: '+64', name: "Pitcairn Islands" },
  { iso: 'PL', code: '+48', name: "Poland" },
  { iso: 'PT', code: '+351', name: "Portugal" },
  { iso: 'PR', code: '+1', name: "Puerto Rico" },
  { iso: 'RE', code: '+262', name: "Réunion" },
  { iso: 'RO', code: '+40', name: "Romania" },
  { iso: 'RU', code: '+7', name: "Russia" },
  { iso: 'RW', code: '+250', name: "Rwanda" },
  { iso: 'WS', code: '+685', name: "Samoa" },
  { iso: 'SM', code: '+378', name: "San Marino" },
  { iso: 'ST', code: '+239', name: "São Tomé & Príncipe" },
  { iso: 'SN', code: '+221', name: "Senegal" },
  { iso: 'RS', code: '+381', name: "Serbia" },
  { iso: 'SC', code: '+248', name: "Seychelles" },
  { iso: 'SL', code: '+232', name: "Sierra Leone" },
  { iso: 'SX', code: '+1', name: "Sint Maarten" },
  { iso: 'SK', code: '+421', name: "Slovakia" },
  { iso: 'SI', code: '+386', name: "Slovenia" },
  { iso: 'SB', code: '+677', name: "Solomon Islands" },
  { iso: 'SO', code: '+252', name: "Somalia" },
  { iso: 'ZA', code: '+27', name: "South Africa" },
  { iso: 'GS', code: '+500', name: "South Georgia & South Sandwich Islands" },
  { iso: 'KR', code: '+82', name: "South Korea" },
  { iso: 'SS', code: '+211', name: "South Sudan" },
  { iso: 'ES', code: '+34', name: "Spain" },
  { iso: 'LK', code: '+94', name: "Sri Lanka" },
  { iso: 'BL', code: '+590', name: "St. Barthélemy" },
  { iso: 'SH', code: '+290', name: "St. Helena" },
  { iso: 'KN', code: '+1', name: "St. Kitts & Nevis" },
  { iso: 'LC', code: '+1', name: "St. Lucia" },
  { iso: 'MF', code: '+590', name: "St. Martin" },
  { iso: 'PM', code: '+508', name: "St. Pierre & Miquelon" },
  { iso: 'VC', code: '+1', name: "St. Vincent & Grenadines" },
  { iso: 'SD', code: '+249', name: "Sudan" },
  { iso: 'SR', code: '+597', name: "Suriname" },
  { iso: 'SJ', code: '+47', name: "Svalbard & Jan Mayen" },
  { iso: 'SE', code: '+46', name: "Sweden" },
  { iso: 'CH', code: '+41', name: "Switzerland" },
  { iso: 'SY', code: '+963', name: "Syria" },
  { iso: 'TW', code: '+886', name: "Taiwan" },
  { iso: 'TJ', code: '+992', name: "Tajikistan" },
  { iso: 'TZ', code: '+255', name: "Tanzania" },
  { iso: 'TH', code: '+66', name: "Thailand" },
  { iso: 'TL', code: '+670', name: "Timor-Leste" },
  { iso: 'TG', code: '+228', name: "Togo" },
  { iso: 'TK', code: '+690', name: "Tokelau" },
  { iso: 'TO', code: '+676', name: "Tonga" },
  { iso: 'TT', code: '+1', name: "Trinidad & Tobago" },
  { iso: 'TN', code: '+216', name: "Tunisia" },
  { iso: 'TR', code: '+90', name: "Türkiye" },
  { iso: 'TM', code: '+993', name: "Turkmenistan" },
  { iso: 'TC', code: '+1', name: "Turks & Caicos Islands" },
  { iso: 'TV', code: '+688', name: "Tuvalu" },
  { iso: 'UG', code: '+256', name: "Uganda" },
  { iso: 'UA', code: '+380', name: "Ukraine" },
  { iso: 'UY', code: '+598', name: "Uruguay" },
  { iso: 'UZ', code: '+998', name: "Uzbekistan" },
  { iso: 'VU', code: '+678', name: "Vanuatu" },
  { iso: 'VA', code: '+39', name: "Vatican City" },
  { iso: 'VE', code: '+58', name: "Venezuela" },
  { iso: 'VN', code: '+84', name: "Vietnam" },
  { iso: 'WF', code: '+681', name: "Wallis & Futuna" },
  { iso: 'EH', code: '+212', name: "Western Sahara" },
  { iso: 'YE', code: '+967', name: "Yemen" },
  { iso: 'ZM', code: '+260', name: "Zambia" },
  { iso: 'ZW', code: '+263', name: "Zimbabwe" },
]

/** The default a form should open on. */
export const DEFAULT_DIAL = '+91'

/** Split "+91 98765 43210" into its code and the rest, for editing an existing value. */
export function splitDial(value) {
  const v = String(value || '').trim()
  if (!v.startsWith('+')) return { code: DEFAULT_DIAL, number: v }
  const hit = DIAL_CODES
    .filter((d) => v.startsWith(d.code))
    .sort((a, b) => b.code.length - a.code.length)[0]
  return hit ? { code: hit.code, number: v.slice(hit.code.length).trim() } : { code: DEFAULT_DIAL, number: v }
}
